# Generated by Django 4.0.4 on 2022-06-16 02:32
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        Language = apps.get_model('language', 'Language')
        data = {
            "hk": "Hong Kong",
            "en": "English"
        }
        for key, value in data:
            language = Language(name = value, short_name = key)
            language.save()

    operations = [
        migrations.RunPython(insertData),
    ]
