# Generated by Django 4.0.4 on 2022-06-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        Language = apps.get_model('language', 'Language')
        data = {
            "hk": "Hong Kong",
            "en": "English"
        }
        for key, value in data.items():
            language = Language(name=str(value), short_name=str(key))
            language.save()

    operations = [
        migrations.RunPython(insertData),
    ]
