# Generated by Django 4.0.4 on 2022-06-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
        Category = apps.get_model('category', 'Category')
        
        for i in range(18):
            category = Category(id=(i+1), active=True)
            category.save()

    operations = [
        migrations.RunPython(insertData),
    ]
