# Generated by Django 4.0.4 on 2022-06-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(blank=True, max_length=100, null=True)),
                ('tue', models.CharField(blank=True, max_length=100, null=True)),
                ('wend', models.CharField(blank=True, max_length=100, null=True)),
                ('thur', models.CharField(blank=True, max_length=100, null=True)),
                ('frid', models.CharField(blank=True, max_length=100, null=True)),
                ('satu', models.CharField(blank=True, max_length=100, null=True)),
                ('sun', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
                'db_table': 'schdule',
            },
        ),
    ]
