# Generated by Django 4.0.4 on 2022-06-16 22:40

from django.db import migrations

from language.models import Language


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('language', '0002_auto_20220616_2223')
    ]

    def insertData(apps, schema_editor):
        District = apps.get_model('district', 'District')

        data = ("Islands",
                "Kwai Tsing",
                "North",
                "Sai Kung",
                "Sha Tin",
                "Tai Po",
                "Tsuen Wan",
                "Tuen Mun",
                "Yuen Long",
                "Kowloon City",
                "Kwun Tong",
                "Sham Shui Po",
                "Wong Tai Sin",
                "Yau Tsim Mong",
                "Central and Western",
                "Eastern",
                "Southern",
                "Wan Chai")

        for value in data:
            district = District(name=value)
            district.save()

    operations = [
        migrations.RunPython(insertData),
    ]
