# Generated by Django 4.0.4 on 2022-06-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=19)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),                
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctor',
                'db_table': 'doctor',
            },
        ),
    ]
